export const FamilyTreeData = [
    { id: 'Jenni Elegard', name: "Jenni Elegard", parents: [], children: ['Alice Duggan', 'Matt Horlock', 'John Burkitt'] },
    { id: 'Alice Duggan', name: "Alice Duggan", parents: ['Jenni Elegard'], children: ['Alex Robertshaw', 'Lien Michiels'] },
    { id: 'Matt Horlock', name: "Matt Horlock", parents: ['Jenni Elegard'], children: ['Adam Wardill', 'Michael Mean', 'Dimitri Papazacharlou'] },
    { id: 'John Burkitt', name: "John Burkitt", parents: ['Jenni Elegard'], children: ['Jake HIllier', 'Lamal Hersheson', 'Will King'] },
    { id: 'Alex Robertshaw', name: "Alex Robertshaw", parents: ['Alice Duggan'], children: [] },
    { id: 'Lien Michiels', name: "Lien Michiels", parents: ['Alice Duggan'], children: [] },
    { id: 'Adam Wardill', name: "Adam Wardill", parents: ['Matt Horlock'], children: [] },
    { id: 'Michael Mean', name: "Michael Mean", parents: ['Matt Horlock'], children: [] },
    { id: 'Dimitri Papazacharlou', name: "Dimitri Papazacharlou", parents: ['Matt Horlock'], children: ['Kine Rydjord', 'Chris Smith', 'Pete Barczak', 'Hannah Jary', 'George Bushby'] },
    { id: 'Jake HIllier', name: "Jake HIllier", parents: ['John Burkitt'], children: [] },
    { id: 'Lamal Hersheson', name: "Lamal Hersheson", parents: ['John Burkitt'], children: [] },
    { id: 'Will King', name: "Will King", parents: ['John Burkitt'], children: ['Richard Bailey', 'Harry Lewis-Irlam', 'Joe Corwan'] },
    { id: 'Kine Rydjord', name: "Kine Rydjord", parents: ['Dimitri Papazacharlou'], children: [] },
    { id: 'Chris Smith', name: "Chris Smith", parents: ['Dimitri Papazacharlou'], children: [] },
    { id: 'Pete Barczak', name: "Pete Barczak", parents: ['Dimitri Papazacharlou'], children: [] },
    { id: 'Hannah Jary', name: "Hannah Jary", parents: ['Dimitri Papazacharlou'], children: [] },
    { id: 'George Bushby', name: "George Bushby", parents: ['Dimitri Papazacharlou'], children: [] },
    { id: 'Richard Bailey', name: "Richard Bailey", parents: ['Will King'], children: ['Luke Jeffries', 'Sapphire Payne'] },
    { id: 'Harry Lewis-Irlam', name: "Harry Lewis-Irlam", parents: ['Will King'], children: ['Ed Williams', 'Vusa Ndlovu', 'Matt A Davies'] },
    { id: 'Joe Corwan', name: "Joe Corwan", parents: ['Will King'], children: ['Tom Nash', 'Sam Sherwood'] },
    { id: 'Luke Jeffries', name: "Luke Jeffries", parents: ['Richard Bailey'], children: [] },
    { id: 'Sapphire Payne', name: "Sapphire Payne", parents: ['Richard Bailey'], children: [] },
    { id: 'Ed Williams', name: "Ed Williams", parents: ['Harry Lewis-Irlam'], children: [] },
    { id: 'Vusa Ndlovu', name: "Vusa Ndlovu", parents: ['Harry Lewis-Irlam'], children: [] },
    { id: 'Matt A Davies', name: "Matt Davies", parents: ['Harry Lewis-Irlam'], children: [] },
    { id: 'Tom Nash', name: "Tom Nash", parents: ['Joe Corwan'], children: [] },
    { id: 'Sam Sherwood', name: "Sam Sherwood", parents: ['Joe Corwan'], children: ['Jack Coope', 'Tom Grainger', 'Alex Brown'] },
    { id: 'Jack Coope', name: "Jack Coope", parents: ['Sam Sherwood'], children: [] },
    { id: 'Tom Grainger', name: "Tom Grainger", parents: ['Sam Sherwood'], children: ['Natalie Lane', 'Kieran Parker', 'Sam Smyth'] },
    { id: 'Alex Brown', name: "Alex Brown", parents: ['Sam Sherwood'], children: ['Holly Arrowsmith', 'Gina Harris'] },
    { id: 'Natalie Lane', name: "Natalie Lane", parents: ['Tom Grainger'], children: [] },
    { id: 'Kieran Parker', name: "Kieran Parker", parents: ['Tom Grainger'], children: ['Paulina Kingmane', 'Joshua Hjowell', 'Harry Ellis', "Liam O'Shea", 'Alex Brown'] },
    { id: 'Sam Smyth', name: "Sam Smyth", parents: ['Tom Grainger'], children: [] },
    { id: 'Holly Arrowsmith', name: "Holly Arrowsmith", parents: ['Alex Brown'], children: [] },
    { id: 'Gina Harris', name: "Gina Harris", parents: ['Alex Brown'], children: [] },
    { id: 'Paulina Kingmane', name: "Paulina Kingmane", parents: ['Kieran Parker'], children: ['Charlie King', 'Emmanuel Ojo'] },
    { id: 'Joshua Hjowell', name: "Joshua Hjowell", parents: ['Kieran Parker'], children: ['Ryan Tomilnson', 'Tom Honer', 'Anish Gurung'] },
    { id: 'Harry Ellis', name: "Harry Ellis", parents: ['Kieran Parker'], children: [] },
    { id: "Liam O'Shea", name: "Liam O'Shea", parents: ['Kieran Parker'], children: ['Richard Ansell', 'Alex Gargrave', 'Ioan Ekland'] },
    { id: 'Alex Brown', name: "Alex Brown", parents: ['Kieran Parker'], children: [] },
    { id: 'Charlie King', name: "Charlie King", parents: ['Paulina Kingmane'], children: [] },
    { id: 'Emmanuel Ojo', name: "Emmanuel Ojo", parents: ['Paulina Kingmane'], children: [] },
    { id: 'Ryan Tomilnson', name: "Ryan Tomilnson", parents: ['Joshua Hjowell'], children: [] },
    { id: 'Tom Honer', name: "Tom Honer", parents: ['Joshua Hjowell'], children: [] },
    { id: 'Anish Gurung', name: "Anish Gurung", parents: ['Joshua Hjowell'], children: [] },
    { id: 'Richard Ansell', name: "Richard Ansell", parents: ["Liam O'Shea"], children: [] },
    { id: 'Alex Gargrave', name: "Alex Gargrave", parents: ["Liam O'Shea"], children: [] },
    { id: 'Ioan Ekland', name: "Ioan Ekland", parents: ["Liam O'Shea"], children: ['Belal Ouachan', 'Matthew Mulvaney'] },
    { id: 'Belal Ouachan', name: "Belal Ouachan", parents: ['Ioan Ekland'], children: [] },
    { id: 'Matthew Mulvaney', name: "Matthew Mulvaney", parents: ['Ioan Ekland'], children: ['Raful', 'Will Moore', 'Callum Pegg', 'Matt B Davies'] },
    { id: 'Raful', name: "Raful", parents: ['Matthew Mulvaney'], children: [] },
    { id: 'Will Moore', name: "Will Moore", parents: ['Matthew Mulvaney'], children: ['Carwyn Draycott'] },
    { id: 'Callum Pegg', name: "Callum Pegg", parents: ['Matthew Mulvaney'], children: ['Patrick Wellings', 'Carlos McFarvey', 'Bracker Payne'] },
    { id: 'Matt B Davies', name: "Matt Davies", parents: ['Matthew Mulvaney'], children: [] },
    { id: 'Carwyn Draycott', name: "Carwyn Draycott", parents: ['Will Moore'], children: ['Felix Rhode'] },
    { id: 'Patrick Wellings', name: "Patrick Wellings", parents: ['Callum Pegg'], children: [] },
    { id: 'Carlos McFarvey', name: "Carlos McFarvey", parents: ['Callum Pegg'], children: [] },
    { id: 'Bracker Payne', name: "Bracker Payne", parents: ['Callum Pegg'], children: [] },
    { id: 'Felix Rhode', name: "Felix Rhode", parents: ['Carwyn Draycott'], children: [] },
    { id: 'Cara Myres', name: "Cara Myres", parents: [], children: ['Jonny Clegg', 'Ian Hunt'] },
    { id: 'Jonny Clegg', name: "Jonny Clegg", parents: ['Cara Myres'], children: [] },
    { id: 'Ian Hunt', name: "Ian Hunt", parents: ['Cara Myres'], children: ['Amy Phillips', 'Luke Quinn'] },
    { id: 'Amy Phillips', name: "Amy Phillips", parents: ['Ian Hunt'], children: [] },
    { id: 'Luke Quinn', name: "Luke Quinn", parents: ['Ian Hunt'], children: ['Matt Swift', 'Mitch Nunn', 'Kieran Reck'] },
    { id: 'Matt Swift', name: "Matt Swift", parents: ['Luke Quinn'], children: [] },
    { id: 'Mitch Nunn', name: "Mitch Nunn", parents: ['Luke Quinn'], children: [] },
    { id: 'Kieran Reck', name: "Kieran Reck", parents: ['Luke Quinn'], children: ['Ellie Roach', 'Gwen Jones', "Clair O'Brien", 'Ben Campbell'] },
    { id: 'Ellie Roach', name: "Ellie Roach", parents: ['Kieran Reck'], children: [] },
    { id: 'Gwen Jones', name: "Gwen Jones", parents: ['Kieran Reck'], children: [] },
    { id: "Clair O'Brien", name: "Clair O'Brien", parents: ['Kieran Reck'], children: [] },
    { id: 'Ben Campbell', name: "Ben Campbell", parents: ['Kieran Reck'], children: ['Ben Thomson', 'Sara Whitehorn', 'Hattie Roxborough', 'Manar Arikat'] },
    { id: 'Ben Thomson', name: "Ben Thomson", parents: ['Ben Campbell'], children: [] },
    { id: 'Sara Whitehorn', name: "Sara Whitehorn", parents: ['Ben Campbell'], children: ['Will Jefferies', 'Will Hickling', 'Neil Luscombe'] },
    { id: 'Hattie Roxborough', name: "Hattie Roxborough", parents: ['Sara Whitehorn'], children: [] },
    { id: 'Manar Arikat', name: "Manar Arikat", parents: ['Sara Whitehorn'], children: [] },
    { id: 'Will Jefferies', name: "Will Jefferies", parents: ['Sara Whitehorn'], children: ['Will Hickling', 'Neil Luscombe'] },
    { id: 'Will Hickling', name: "Will Hickling", parents: ['Will Jefferies'], children: [] },
    { id: 'Neil Luscombe', name: "Neil Luscombe", parents: ['Will Jefferies'], children: ['Joe Trigg', 'Kelly Charlton', 'Kayleigh Marks', 'Jamie Pain'] },
    { id: 'Joe Trigg', name: "Joe Trigg", parents: ['Neil Luscombe'], children: [] },
    { id: 'Kelly Charlton', name: "Kelly Charlton", parents: ['Neil Luscombe'], children: [] },
    { id: 'Kayleigh Marks', name: "Kayleigh Marks", parents: ['Neil Luscombe'], children: ['Jayden Olden'] },
    { id: 'Jayden Olden', name: "Jayden Olden", parents: ['Kayleigh Marks'], children: ['82', 'Zade Azzi'] },
    { id: 'Sam Le Marquand', name: "Sam Le Marquand", parents: ['Jayden Olden'], children: [] },
    { id: 'Zade Azzi', name: "Zade Azzi", parents: ['Jayden Olden'], children: [] },
    { id: 'Jamie Pain', name: "Jamie Pain", parents: ['Neil Luscombe'], children: ['Dan Lindsley'] },
    { id: 'Dan Lindsley', name: "Dan Lindsley", parents: ['Jamie Pain'], children: ['Kai Pettifer', 'Megan Johns'] },
    { id: 'Kai Pettifer', name: "Kai Pettifer", parents: ['Dan Lindsley'], children: ['James Smith', 'Hollie Hughes', 'Matt Simmons'] },
    { id: 'Megan Johns', name: "Megan Johns", parents: ['Dan Lindsley'], children: [] },
    { id: 'James Smith', name: "James Smith", parents: ['Kai Pettifer'], children: [] },
    { id: 'Hollie Hughes', name: "Hollie Hughes", parents: ['Kai Pettifer'], children: [] },
    { id: 'Matt Simmons', name: "Matt Simmons", parents: ['Kai Pettifer'], children: [] },
    { id: 'Heidi Erhe', name: "Heidi Erhe", parents: [], children: ['Antonio Sawaya', 'Max Deeble', 'Emily Seaman'] },
    { id: 'Antonio Sawaya', name: "Antonio Sawaya", parents: ['Heidi Erhe'], children: [] },
    { id: 'Max Deeble', name: "Max Deeble", parents: ['Heidi Erhe'], children: [] },
    { id: 'Emily Seaman', name: "Emily Seaman", parents: ['Heidi Erhe'], children: ['Callum Rail', 'Jordan Wright', 'Ben Gooding'] },
    { id: 'Callum Rail', name: "Callum Rail", parents: ['Emily Seaman'], children: [] },
    { id: 'Jordan Wright', name: "Jordan Wright", parents: ['Emily Seaman'], children: [] },
    { id: 'Ben Gooding', name: "Ben Gooding", parents: ['Emily Seaman'], children: ['Alexi Antoniou', 'Anna Elson'] },
    { id: 'Alexi Atoniou', name: "Alexi Antoniou", parents: ['Ben Gooding'], children: [] },
    { id: 'Anna Elson', name: "Anna Elson", parents: ['Ben Gooding'], children: ['Lauren Bostic'] },
    { id: 'Lauren Bostic', name: "Lauren Bostic", parents: ['Anna Elson'], children: ['Henry Jackson', 'Tara Morgan'] },
    { id: 'Henry Jackson', name: "Henry Jackson", parents: ['Lauren Bostic'], children: [] },
    { id: 'Tara Morgan', name: "Tara Morgan", parents: ['Lauren Bostic'], children: ['Rebbecca Downey'] },
    { id: 'Rebbecca Downey', name: "Rebbecca Downey", parents: ['Tara Morgan'], children: ['Crispin Low'] },
    { id: 'Crispin Low', name: "Crispin Low", parents: ['Rebbecca Downey'], children: ['Rob Winton'] },
    { id: 'Rob Winton', name: "Rob Winton", parents: ['Crispin Low'], children: [] },
    { id: 'Nick Conan', name: "Nick Conan", parents: [], children: ['Carl Bashford'] },
    { id: 'Carl Bashford', name: "Carl Bashford", parents: ['Nick Conan'], children: ['Josie Manley', 'Mark Forrester', 'James Joy'] },
    { id: 'Josie Manley', name: "Josie Manley", parents: ['Carl Bashford'], children: [] },
    { id: 'Mark Forrester', name: "Mark Forrester", parents: ['Carl Bashford'], children: ['Howard Richards', 'Joe Smith', 'Matt Galvin'] },
    { id: 'James Joy', name: "James Joy", parents: ['Carl Bashford'], children: ['Matt HollyHurst', 'Siamak Rezazadeh', 'Gemma Gorrie', 'Roberto Payne'] },
    { id: 'Howard Richards', name: "Howard Richards", parents: ['Mark Forrester'], children: [] },
    { id: 'Joe Smith', name: "Joe Smith", parents: ['Mark Forrester'], children: [] },
    { id: 'Matt Galvin', name: "Matt Galvin", parents: ['Mark Forrester'], children: [] },
    { id: 'Matt HollyHurst', name: "Matt Hollyhurst", parents: ['James Joy'], children: [] },
    { id: 'Siamak Rezazadeh', name: "Siamak Rezazadeh", parents: ['James Joy'], children: [] },
    { id: 'Gemma Gorrie', name: "Gemma Gorrie", parents: ['James Joy'], children: [] },
    { id: 'Roberto Payne', name: "Roberto Payne", parents: ['James Joy'], children: ['Steve Bates'] },
    { id: 'Steve Bates', name: "Steve Bates", parents: ['Roberto Payne'], children: [] },
    { id: 'Joe Hollyhurst', name: "Joe Hollyhurst", parents: ['Roberto Payne'], children: ['Lydia Davies'] },
    { id: 'Lydia Davies', name: "Lydia Davies", parents: ['Joe Hollyhurst'], children: ['Ioana Pidgen', 'Riley Hagen', 'Erin Good'] },
    { id: 'Ioana Pidgen', name: "Iona Pidgen", parents: ['Lydia Davies'], children: [] },
    { id: 'Riley Hagen', name: "Riley Hagen", parents: ['Lydia Davies'], children: ['Ethan Humphries', 'Mikel Walsh', 'Adam Case-Legge'] },
    { id: 'Erin Good', name: "Erin Good", parents: ['Lydia Davies'], children: ['Alex Stratton'] },
    { id: 'Ethan Humphries', name: "Ethan Humphries", parents: ['Riley Hagen'], children: [] },
    { id: 'Mikel Walsh', name: "Mikel Walsh", parents: ['Riley Hagen'], children: ['Ryan Constable', 'Jae Taylor', 'Alex Muffet'] },
    { id: 'Adam Case-Legge', name: "Adam Case-Legge", parents: ['Riley Hagen'], children: ['Chris Baynes', 'Sam Richardon', 'Ben Barthomolew'] },
    { id: 'Alex Stratton', name: "Alex Stratton", parents: ['Erin Good'], children: ['Shalika De Freitas'] },
    { id: 'Ryan Constable', name: "Ryan Constable", parents: ['Mikel Walsh'], children: [] },
    { id: 'Jae Taylor', name: "Jae Taylor", parents: ['Mikel Walsh'], children: [] },
    { id: 'Alex Muffet', name: "Alex Muffet", parents: ['Mikel Walsh'], children: [] },
    { id: 'Chris Baynes', name: "Chris Baynes", parents: ['Adam Case-Legge'], children: ['Ella Silvester', 'Tom Lacey'] },
    { id: 'Sam Richardon', name: "Sam Richardon", parents: ['Adam Case-Legge'], children: ['Maeve Cotter'] },
    { id: 'Ben Barthomolew', name: "Ben Barthomolew", parents: ['Adam Case-Legge'], children: ['Gracie Pratchett', 'Havish Patel'] },
    { id: 'Shalika De Freitas', name: "Shalika De Freitas", parents: ['Alex Stratton'], children: [] },
    { id: 'Ella Silvester', name: "Ella Silvester", parents: ['Chris Baynes'], children: [] },
    { id: 'Tom Lacey', name: "Tom Lacey", parents: ['Chris Baynes'], children: [] },
    { id: 'Maeve Cotter', name: "Maeve Cotter", parents: ['Sam Richardon'], children: [] },
    { id: 'Gracie Pratchett', name: "Gracie Pratchett", parents: ['Ben Barthomolew'], children: [] },
    { id: 'Havish Patel', name: "Havish Patel", parents: ['Ben Barthomolew'], children: [] },
    { id: 'Alex McFarlane', name: "Alex McFarlane", parents: [], children: ['Dan Warden', 'Jamie Dartnell'] },
    { id: 'Dan Warden', name: "Dan Warden", parents: ['Alex McFarlane'], children: [] },
    { id: 'Jamie Dartnell', name: "Jamie Dartnell", parents: ['Alex McFarlane'], children: ['Sully Butt', 'Jonathan Montanarini'] },
    { id: 'Sully Butt', name: "Sully Butt", parents: ['Jamie Dartnell'], children: [] },
    { id: 'Jonathan Montanarini', name: "Jonathan Montanarini", parents: ['Jamie Dartnell'], children: ['Dom Wigginton', 'Rhian Williams'] },
    { id: 'Dom Wigginton', name: "Dom Wigginton", parents: ['Jonathan Montanarini'], children: [] },
    { id: 'Rhian Williams', name: "Rhian Williams", parents: ['Jonathan Montanarini'], children: ['Charlotte Skilton', 'Jessica Perez'] },
    { id: 'Charlotte Skilton', name: "Charlotte Skilton", parents: ['Rhian Williams'], children: ['Sujan Jesuraja', 'Meera Bhudia'] },
    { id: 'Jessica Perez', name: "Jessica Perez", parents: ['Rhian Williams'], children: ['Asia Browne', 'Jodie Hannaford'] },
    { id: 'George Slade', name: "George Slade", parents: [], children: ['Jacob Weller'] },
    { id: 'Nick Gudgeon', name: "Nick Gudgeon", parents: [], children: ['Jamie Dowie'] },
    { id: 'Sujan Jesuraja', name: "Sujan Jesuraja", parents: ['Charlotte Skilton'], children: [] },
    { id: 'Meera Bhudia', name: 'Meera Bhudia', parents: ['Charlotte Skilton'], children: ['Keeley Barnes', 'Mariam Daniel', 'Charlotte Arulseelan']},
    { id: 'Keeley Barnes', name: "Keeley Barnes", parents: ['Meera Bhudia'], children: [] },
    { id: 'Mariam Daniel', name: "Mariam Daniel", parents: ['Meera Bhudia'], children: ['Grace Alice'] },
    { id: 'Asia Browne', name: "Asia Browne", parents: ['Jessica Perez'], children: [] },
    { id: 'Jodie Hannaford', name: "Jodie Hannaford", parents: ['Jessica Perez'], children: ['Victoria Patching', 'Emili Satachan'] },
    { id: 'Grace Alice', name: "Grace Alice", parents: ['Mariam Daniel'], children: [] },
    { id: 'Charlotte Arulseelan', name: 'Charlotte Arulseelan', parents: ['Meera Bhudia'], children: ['Megan Shipton', 'Clara Hanion', 'Jacob Rufus']},
    { id: 'Megan Shipton', name: "Megan Shipton", parents: ['Charlotte Arulseelan'], children: [] },
    { id: 'Clara Hanion', name: "Clara Hanion", parents: ['Charlotte Arulseelan'], children: [] },
    { id: 'Jacob Rufus', name: 'Jacob Rufus', parents: ['Charlotte Arulseelan'], children: ['Nat Wannapon']},
    { id: 'Nat Wannapon', name: "Nat Wannapon", parents: ['Jacob Rufus'], children: ['Ollie Bennett', 'Ellie larkann-Kay', 'Humza Butt'] },
    { id: 'Victoria Patching', name: "Victoria Patching", parents: ['Jodie Hannaford'], children: [] },
    { id: 'Emili Satachan', name: "Emili Satachan", parents: ['Jodie Hannaford'], children: ['Kelsey Fernandes'] },
    { id: 'Ollie Bennett', name: "Ollie Bennett", parents: ['Nat Wannapon'], children: [] },
    { id: 'Ellie larkann-Kay', name: "Ellie Larkann-Kay", parents: ['Nat Wannapon'], children: [] },
    { id: 'Humza Butt', name: "Humza Butt", parents: ['Nat Wannapon'], children: ['Ali Hamm', 'James W', 'Caitlin Lubbe'] },
    { id: 'Kelsey Fernandes', name: "Kelsey Fernandes", parents: ['Emili Satachan'], children: ['Charlotte Minchell'] },
    { id: 'Ali Hamm', name: "Ali Hamm", parents: ['Humza Butt'], children: [] },
    { id: 'James W', name: "James W", parents: ['Humza Butt'], children: [] },
    { id: 'Caitlin Lubbe', name: "Caitlin Lubbe", parents: ['Humza Butt'], children: [] },
    { id: 'Charlotte Minchell', name: "Charlotte Minchell", parents: ['Kelsey Fernandes'], children: [] },
    { id: 'Jacob Weller', name: "Jacob Weller", parents: ['George Slade'], children: ['Jamie Dowie', 'Wes Richardson'] },
    { id: 'Jamie Dowie', name: "Jamie Dowie", parents: ['Nick Gudgeon'], children: ['Samantha Hoose', 'George Whitley'] },
    { id: 'Wes Richardson', name: "Wes Richardson", parents: ['Jacob Weller'], children: ['Adam Farrell', 'Ollie Batchelor', 'Victoria Boyce', 'Valeria Petrine'] },
    { id: 'Samantha Hoose', name: "Samantha Hoose", parents: ['Jamie Dowie'], children: ['Nico Marshallneck', 'Alex Wagner', 'Sam Jones', 'Shannon Cruse'] },
    { id: 'George Whitley', name: "George Whitley", parents: ['Jamie Dowie'], children: ['James Greenough', 'Sam Elimers', 'Scott Burd'] },
    { id: 'Adam Farrell', name: "Adam Farrell", parents: ['Wes Richardson'], children: [] },
    { id: 'Ollie Batchelor', name: "Ollie Batchelor", parents: ['Wes Richardson'], children: [] },
    { id: 'Victoria Boyce', name: "Victoria Boyce", parents: ['Wes Richardson'], children: [] },
    { id: 'Valeria Petrine', name: "Valeria Petrine", parents: ['Wes Richardson'], children: ['Scott Price', 'Tom Hall', 'Scott Hazelwood', 'Gary Alderman'] },
    { id: 'Nico Marshallneck', name: "Nico Marshalleck", parents: ['Samantha Hoose'], children: [] },
    { id: 'Alex Wagner', name: "Alex Wagner", parents: ['Samantha Hoose'], children: [] },
    { id: 'Sam Jones', name: "Sam Jones", parents: ['Samantha Hoose'], children: [] },
    { id: 'Shannon Cruse', name: "Shannon Cruse", parents: ['Samantha Hoose'], children: [] },
    { id: 'James Greenough', name: "James Greenough", parents: ['George Whitley'], children: [] },
    { id: 'Sam Elimers', name: "Sam Elimers", parents: ['George Whitley'], children: [] },
    { id: 'Scott Burd', name: "Scott Burd", parents: ['George Whitley'], children: ['Scott Price'] },
    { id: 'Scott Price', name: "Scott Price", parents: ['Scott Burd'], children: ['Tom Hall'] },
    { id: 'Tom Hall', name: "Tom Hall", parents: ['Scott Price'], children: ['Scott Hazelwood'] },
    { id: 'Scott Hazelwood', name: "Scott Hazelwood", parents: ['Tom Hall'], children: [] },
    { id: 'Gary Alderman', name: "Gary Alderman", parents: ['Valeria Petrine'], children: [] },
    { id: 'Brigita Tamsauskaite', name: "Brigita Tamsauskaite", parents: ['Valeria Petrine'], children: [] },
    { id: 'Sophie', name: "Sophie", parents: ['Valeria Petrine'], children: [] },
    { id: 'Simon Casswell', name: "Simon Casswell", parents: ['Valeria Petrine'], children: ['Tommy Lee-Nathan'] },
    { id: 'Tommy Lee-Nathan', name: "Tommy Lee-Nathan", parents: ['Simon Casswell'], children: [] },
    { id: 'Johnny Crook', name: "Johnny Crook", parents: [], children: ["Eoin O'Leary"] },
    { id: "Eoin O'Leary", name: "Eoin O'Leary", parents: ['Johnny Crook'], children: [] },
    { id: 'Alex Rose', name: "Alex Rose", parents: [], children: ['Matt Wraight'] },
    { id: 'Matt Wraight', name: "Matt Wraight", parents: ['Alex Rose'], children: ['Georgie Watson'] },
    { id: 'Georgie Watson', name: "Georgie Watson", parents: ['Matt Wraight'], children: [] },
    { id: 'Julian Zarzoso-Lowe', name: "Julian Zarzoso-Lowe", parents: [], children: ['Alice Whittal', 'Callum Harrison'] },
    { id: 'Alice Whittal', name: "Alice Whittal", parents: ['Julian Zarzoso-Lowe'], children: [] },
    { id: 'Callum Harrison', name: "Callum Harrison", parents: ['Julian Zarzoso-Lowe'], children: ['John Eveleigh'] },
    { id: 'John Eveleigh', name: "John Eveleigh", parents: ['Callum Harrison'], children: ['Lauren Stockley', 'Chris Thornton', 'Jack Gale'] },
    { id: 'Lauren Stockley', name: "Lauren Stockley", parents: ['John Eveleigh'], children: [] },
    { id: 'Chris Thornton', name: "Chris Thornton", parents: ['John Eveleigh'], children: [] },
    { id: 'Jack Gale', name: "Jack Gale", parents: ['John Eveleigh'], children: [] },    
  ];

  export default FamilyTreeData;